// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen-builder; DO NOT EDIT.

// RegionBuilder registers per-hook callbacks instead of implementing the full
// RegionObserver interface. Regenerate: go generate ./pkg/hbasecop

package hbasecop

import (
	"context"

	"github.com/virogg/go-hbase/internal/wire/hookpb"
)

// RegionBuilder is a RegionObserver assembled from per-hook closures; unset hooks are
// no-ops. Build with NewRegion and the On* setters, then pass to Run.
type RegionBuilder struct {
	UnimplementedRegionObserver
	preOpen                                 func(ctx context.Context, env ObserverEnv, req *hookpb.PreOpenRequest) (HookResult, error)
	postOpen                                func(ctx context.Context, env ObserverEnv, req *hookpb.PostOpenRequest) error
	preClose                                func(ctx context.Context, env ObserverEnv, req *hookpb.PreCloseRequest) (HookResult, error)
	postClose                               func(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRequest) error
	preFlush                                func(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushRequest) (HookResult, error)
	preFlushScannerOpen                     func(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushScannerOpenRequest) (HookResult, error)
	postFlush                               func(ctx context.Context, env ObserverEnv, req *hookpb.PostFlushRequest) error
	preMemStoreCompaction                   func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionRequest) (HookResult, error)
	preMemStoreCompactionCompactScannerOpen func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactScannerOpenRequest) (HookResult, error)
	preMemStoreCompactionCompact            func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactRequest) (HookResult, error)
	postMemStoreCompaction                  func(ctx context.Context, env ObserverEnv, req *hookpb.PostMemStoreCompactionRequest) error
	preCompactSelection                     func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactSelectionRequest) (HookResult, error)
	postCompactSelection                    func(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactSelectionRequest) error
	preCompactScannerOpen                   func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactScannerOpenRequest) (HookResult, error)
	preCompact                              func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactRequest) (HookResult, error)
	postCompact                             func(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactRequest) error
	preGetOp                                func(ctx context.Context, env ObserverEnv, req *hookpb.PreGetOpRequest) (HookResult, error)
	postGetOp                               func(ctx context.Context, env ObserverEnv, req *hookpb.PostGetOpRequest) error
	preExists                               func(ctx context.Context, env ObserverEnv, req *hookpb.PreExistsRequest) (HookResult, error)
	postExists                              func(ctx context.Context, env ObserverEnv, req *hookpb.PostExistsRequest) error
	prePut                                  func(ctx context.Context, env ObserverEnv, mutation *MutationProto) (HookResult, error)
	postPut                                 func(ctx context.Context, env ObserverEnv, mutation *MutationProto) error
	preDelete                               func(ctx context.Context, env ObserverEnv, req *hookpb.PreDeleteRequest) (HookResult, error)
	postDelete                              func(ctx context.Context, env ObserverEnv, req *hookpb.PostDeleteRequest) error
	prePrepareTimeStampForDeleteVersion     func(ctx context.Context, env ObserverEnv, req *hookpb.PrePrepareTimeStampForDeleteVersionRequest) (HookResult, error)
	preBatchMutate                          func(ctx context.Context, env ObserverEnv, req *hookpb.PreBatchMutateRequest) (HookResult, error)
	postBatchMutate                         func(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateRequest) error
	postBatchMutateIndispensably            func(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateIndispensablyRequest) error
	postStartRegionOperation                func(ctx context.Context, env ObserverEnv, req *hookpb.PostStartRegionOperationRequest) error
	postCloseRegionOperation                func(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRegionOperationRequest) error
	preCheckAndPut                          func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutRequest) (HookResult, error)
	postCheckAndPut                         func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndPutRequest) error
	preCheckAndPutAfterRowLock              func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutAfterRowLockRequest) (HookResult, error)
	preCheckAndDelete                       func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteRequest) (HookResult, error)
	postCheckAndDelete                      func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndDeleteRequest) error
	preCheckAndDeleteAfterRowLock           func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteAfterRowLockRequest) (HookResult, error)
	preCheckAndMutate                       func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateRequest) (HookResult, error)
	postCheckAndMutate                      func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndMutateRequest) error
	preCheckAndMutateAfterRowLock           func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateAfterRowLockRequest) (HookResult, error)
	preAppend                               func(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendRequest) (HookResult, error)
	postAppend                              func(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendRequest) error
	preAppendAfterRowLock                   func(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendAfterRowLockRequest) (HookResult, error)
	preIncrement                            func(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementRequest) (HookResult, error)
	postIncrement                           func(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementRequest) error
	preIncrementAfterRowLock                func(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementAfterRowLockRequest) (HookResult, error)
	preScannerOpen                          func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerOpenRequest) (HookResult, error)
	postScannerOpen                         func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerOpenRequest) error
	preScannerNext                          func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerNextRequest) (HookResult, error)
	postScannerNext                         func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerNextRequest) error
	postScannerFilterRow                    func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerFilterRowRequest) error
	preScannerClose                         func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerCloseRequest) (HookResult, error)
	postScannerClose                        func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerCloseRequest) error
	preStoreScannerOpen                     func(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreScannerOpenRequest) (HookResult, error)
	preReplayWALs                           func(ctx context.Context, env ObserverEnv, req *hookpb.PreReplayWALsRequest) (HookResult, error)
	postReplayWALs                          func(ctx context.Context, env ObserverEnv, req *hookpb.PostReplayWALsRequest) error
	preWALRestore                           func(ctx context.Context, env ObserverEnv, req *hookpb.PreWALRestoreRequest) (HookResult, error)
	postWALRestore                          func(ctx context.Context, env ObserverEnv, req *hookpb.PostWALRestoreRequest) error
	preBulkLoadHFile                        func(ctx context.Context, env ObserverEnv, req *hookpb.PreBulkLoadHFileRequest) (HookResult, error)
	postBulkLoadHFile                       func(ctx context.Context, env ObserverEnv, req *hookpb.PostBulkLoadHFileRequest) error
	preCommitStoreFile                      func(ctx context.Context, env ObserverEnv, req *hookpb.PreCommitStoreFileRequest) (HookResult, error)
	postCommitStoreFile                     func(ctx context.Context, env ObserverEnv, req *hookpb.PostCommitStoreFileRequest) error
	preStoreFileReaderOpen                  func(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreFileReaderOpenRequest) (HookResult, error)
	postStoreFileReaderOpen                 func(ctx context.Context, env ObserverEnv, req *hookpb.PostStoreFileReaderOpenRequest) error
	postMutationBeforeWAL                   func(ctx context.Context, env ObserverEnv, req *hookpb.PostMutationBeforeWALRequest) error
	postIncrementBeforeWAL                  func(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementBeforeWALRequest) error
	postAppendBeforeWAL                     func(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendBeforeWALRequest) error
	postInstantiateDeleteTracker            func(ctx context.Context, env ObserverEnv, req *hookpb.PostInstantiateDeleteTrackerRequest) error
	preWALAppend                            func(ctx context.Context, env ObserverEnv, req *hookpb.PreWALAppendRequest) (HookResult, error)
}

var _ RegionObserver = (*RegionBuilder)(nil)

// NewRegion returns an empty RegionBuilder.
func NewRegion() *RegionBuilder { return &RegionBuilder{} }

// OnPreOpen registers the PreOpen callback.
func (b *RegionBuilder) OnPreOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preOpen = fn
	return b
}

func (b *RegionBuilder) PreOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreOpenRequest) (HookResult, error) {
	if b.preOpen != nil {
		return b.preOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostOpen registers the PostOpen callback.
func (b *RegionBuilder) OnPostOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostOpenRequest) error) *RegionBuilder {
	b.postOpen = fn
	return b
}

func (b *RegionBuilder) PostOpen(ctx context.Context, env ObserverEnv, req *hookpb.PostOpenRequest) error {
	if b.postOpen != nil {
		return b.postOpen(ctx, env, req)
	}
	return nil
}

// OnPreClose registers the PreClose callback.
func (b *RegionBuilder) OnPreClose(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCloseRequest) (HookResult, error)) *RegionBuilder {
	b.preClose = fn
	return b
}

func (b *RegionBuilder) PreClose(ctx context.Context, env ObserverEnv, req *hookpb.PreCloseRequest) (HookResult, error) {
	if b.preClose != nil {
		return b.preClose(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostClose registers the PostClose callback.
func (b *RegionBuilder) OnPostClose(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRequest) error) *RegionBuilder {
	b.postClose = fn
	return b
}

func (b *RegionBuilder) PostClose(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRequest) error {
	if b.postClose != nil {
		return b.postClose(ctx, env, req)
	}
	return nil
}

// OnPreFlush registers the PreFlush callback.
func (b *RegionBuilder) OnPreFlush(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushRequest) (HookResult, error)) *RegionBuilder {
	b.preFlush = fn
	return b
}

func (b *RegionBuilder) PreFlush(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushRequest) (HookResult, error) {
	if b.preFlush != nil {
		return b.preFlush(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreFlushScannerOpen registers the PreFlushScannerOpen callback.
func (b *RegionBuilder) OnPreFlushScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushScannerOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preFlushScannerOpen = fn
	return b
}

func (b *RegionBuilder) PreFlushScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreFlushScannerOpenRequest) (HookResult, error) {
	if b.preFlushScannerOpen != nil {
		return b.preFlushScannerOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostFlush registers the PostFlush callback.
func (b *RegionBuilder) OnPostFlush(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostFlushRequest) error) *RegionBuilder {
	b.postFlush = fn
	return b
}

func (b *RegionBuilder) PostFlush(ctx context.Context, env ObserverEnv, req *hookpb.PostFlushRequest) error {
	if b.postFlush != nil {
		return b.postFlush(ctx, env, req)
	}
	return nil
}

// OnPreMemStoreCompaction registers the PreMemStoreCompaction callback.
func (b *RegionBuilder) OnPreMemStoreCompaction(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionRequest) (HookResult, error)) *RegionBuilder {
	b.preMemStoreCompaction = fn
	return b
}

func (b *RegionBuilder) PreMemStoreCompaction(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionRequest) (HookResult, error) {
	if b.preMemStoreCompaction != nil {
		return b.preMemStoreCompaction(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreMemStoreCompactionCompactScannerOpen registers the PreMemStoreCompactionCompactScannerOpen callback.
func (b *RegionBuilder) OnPreMemStoreCompactionCompactScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactScannerOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preMemStoreCompactionCompactScannerOpen = fn
	return b
}

func (b *RegionBuilder) PreMemStoreCompactionCompactScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactScannerOpenRequest) (HookResult, error) {
	if b.preMemStoreCompactionCompactScannerOpen != nil {
		return b.preMemStoreCompactionCompactScannerOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreMemStoreCompactionCompact registers the PreMemStoreCompactionCompact callback.
func (b *RegionBuilder) OnPreMemStoreCompactionCompact(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactRequest) (HookResult, error)) *RegionBuilder {
	b.preMemStoreCompactionCompact = fn
	return b
}

func (b *RegionBuilder) PreMemStoreCompactionCompact(ctx context.Context, env ObserverEnv, req *hookpb.PreMemStoreCompactionCompactRequest) (HookResult, error) {
	if b.preMemStoreCompactionCompact != nil {
		return b.preMemStoreCompactionCompact(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostMemStoreCompaction registers the PostMemStoreCompaction callback.
func (b *RegionBuilder) OnPostMemStoreCompaction(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostMemStoreCompactionRequest) error) *RegionBuilder {
	b.postMemStoreCompaction = fn
	return b
}

func (b *RegionBuilder) PostMemStoreCompaction(ctx context.Context, env ObserverEnv, req *hookpb.PostMemStoreCompactionRequest) error {
	if b.postMemStoreCompaction != nil {
		return b.postMemStoreCompaction(ctx, env, req)
	}
	return nil
}

// OnPreCompactSelection registers the PreCompactSelection callback.
func (b *RegionBuilder) OnPreCompactSelection(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactSelectionRequest) (HookResult, error)) *RegionBuilder {
	b.preCompactSelection = fn
	return b
}

func (b *RegionBuilder) PreCompactSelection(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactSelectionRequest) (HookResult, error) {
	if b.preCompactSelection != nil {
		return b.preCompactSelection(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCompactSelection registers the PostCompactSelection callback.
func (b *RegionBuilder) OnPostCompactSelection(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactSelectionRequest) error) *RegionBuilder {
	b.postCompactSelection = fn
	return b
}

func (b *RegionBuilder) PostCompactSelection(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactSelectionRequest) error {
	if b.postCompactSelection != nil {
		return b.postCompactSelection(ctx, env, req)
	}
	return nil
}

// OnPreCompactScannerOpen registers the PreCompactScannerOpen callback.
func (b *RegionBuilder) OnPreCompactScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactScannerOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preCompactScannerOpen = fn
	return b
}

func (b *RegionBuilder) PreCompactScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactScannerOpenRequest) (HookResult, error) {
	if b.preCompactScannerOpen != nil {
		return b.preCompactScannerOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreCompact registers the PreCompact callback.
func (b *RegionBuilder) OnPreCompact(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactRequest) (HookResult, error)) *RegionBuilder {
	b.preCompact = fn
	return b
}

func (b *RegionBuilder) PreCompact(ctx context.Context, env ObserverEnv, req *hookpb.PreCompactRequest) (HookResult, error) {
	if b.preCompact != nil {
		return b.preCompact(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCompact registers the PostCompact callback.
func (b *RegionBuilder) OnPostCompact(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactRequest) error) *RegionBuilder {
	b.postCompact = fn
	return b
}

func (b *RegionBuilder) PostCompact(ctx context.Context, env ObserverEnv, req *hookpb.PostCompactRequest) error {
	if b.postCompact != nil {
		return b.postCompact(ctx, env, req)
	}
	return nil
}

// OnPreGetOp registers the PreGetOp callback.
func (b *RegionBuilder) OnPreGetOp(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreGetOpRequest) (HookResult, error)) *RegionBuilder {
	b.preGetOp = fn
	return b
}

func (b *RegionBuilder) PreGetOp(ctx context.Context, env ObserverEnv, req *hookpb.PreGetOpRequest) (HookResult, error) {
	if b.preGetOp != nil {
		return b.preGetOp(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostGetOp registers the PostGetOp callback.
func (b *RegionBuilder) OnPostGetOp(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostGetOpRequest) error) *RegionBuilder {
	b.postGetOp = fn
	return b
}

func (b *RegionBuilder) PostGetOp(ctx context.Context, env ObserverEnv, req *hookpb.PostGetOpRequest) error {
	if b.postGetOp != nil {
		return b.postGetOp(ctx, env, req)
	}
	return nil
}

// OnPreExists registers the PreExists callback.
func (b *RegionBuilder) OnPreExists(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreExistsRequest) (HookResult, error)) *RegionBuilder {
	b.preExists = fn
	return b
}

func (b *RegionBuilder) PreExists(ctx context.Context, env ObserverEnv, req *hookpb.PreExistsRequest) (HookResult, error) {
	if b.preExists != nil {
		return b.preExists(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostExists registers the PostExists callback.
func (b *RegionBuilder) OnPostExists(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostExistsRequest) error) *RegionBuilder {
	b.postExists = fn
	return b
}

func (b *RegionBuilder) PostExists(ctx context.Context, env ObserverEnv, req *hookpb.PostExistsRequest) error {
	if b.postExists != nil {
		return b.postExists(ctx, env, req)
	}
	return nil
}

// OnPrePut registers the PrePut callback.
func (b *RegionBuilder) OnPrePut(fn func(ctx context.Context, env ObserverEnv, mutation *MutationProto) (HookResult, error)) *RegionBuilder {
	b.prePut = fn
	return b
}

func (b *RegionBuilder) PrePut(ctx context.Context, env ObserverEnv, mutation *MutationProto) (HookResult, error) {
	if b.prePut != nil {
		return b.prePut(ctx, env, mutation)
	}
	return HookResult{}, nil
}

// OnPostPut registers the PostPut callback.
func (b *RegionBuilder) OnPostPut(fn func(ctx context.Context, env ObserverEnv, mutation *MutationProto) error) *RegionBuilder {
	b.postPut = fn
	return b
}

func (b *RegionBuilder) PostPut(ctx context.Context, env ObserverEnv, mutation *MutationProto) error {
	if b.postPut != nil {
		return b.postPut(ctx, env, mutation)
	}
	return nil
}

// OnPreDelete registers the PreDelete callback.
func (b *RegionBuilder) OnPreDelete(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreDeleteRequest) (HookResult, error)) *RegionBuilder {
	b.preDelete = fn
	return b
}

func (b *RegionBuilder) PreDelete(ctx context.Context, env ObserverEnv, req *hookpb.PreDeleteRequest) (HookResult, error) {
	if b.preDelete != nil {
		return b.preDelete(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostDelete registers the PostDelete callback.
func (b *RegionBuilder) OnPostDelete(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostDeleteRequest) error) *RegionBuilder {
	b.postDelete = fn
	return b
}

func (b *RegionBuilder) PostDelete(ctx context.Context, env ObserverEnv, req *hookpb.PostDeleteRequest) error {
	if b.postDelete != nil {
		return b.postDelete(ctx, env, req)
	}
	return nil
}

// OnPrePrepareTimeStampForDeleteVersion registers the PrePrepareTimeStampForDeleteVersion callback.
func (b *RegionBuilder) OnPrePrepareTimeStampForDeleteVersion(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PrePrepareTimeStampForDeleteVersionRequest) (HookResult, error)) *RegionBuilder {
	b.prePrepareTimeStampForDeleteVersion = fn
	return b
}

func (b *RegionBuilder) PrePrepareTimeStampForDeleteVersion(ctx context.Context, env ObserverEnv, req *hookpb.PrePrepareTimeStampForDeleteVersionRequest) (HookResult, error) {
	if b.prePrepareTimeStampForDeleteVersion != nil {
		return b.prePrepareTimeStampForDeleteVersion(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreBatchMutate registers the PreBatchMutate callback.
func (b *RegionBuilder) OnPreBatchMutate(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreBatchMutateRequest) (HookResult, error)) *RegionBuilder {
	b.preBatchMutate = fn
	return b
}

func (b *RegionBuilder) PreBatchMutate(ctx context.Context, env ObserverEnv, req *hookpb.PreBatchMutateRequest) (HookResult, error) {
	if b.preBatchMutate != nil {
		return b.preBatchMutate(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostBatchMutate registers the PostBatchMutate callback.
func (b *RegionBuilder) OnPostBatchMutate(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateRequest) error) *RegionBuilder {
	b.postBatchMutate = fn
	return b
}

func (b *RegionBuilder) PostBatchMutate(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateRequest) error {
	if b.postBatchMutate != nil {
		return b.postBatchMutate(ctx, env, req)
	}
	return nil
}

// OnPostBatchMutateIndispensably registers the PostBatchMutateIndispensably callback.
func (b *RegionBuilder) OnPostBatchMutateIndispensably(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateIndispensablyRequest) error) *RegionBuilder {
	b.postBatchMutateIndispensably = fn
	return b
}

func (b *RegionBuilder) PostBatchMutateIndispensably(ctx context.Context, env ObserverEnv, req *hookpb.PostBatchMutateIndispensablyRequest) error {
	if b.postBatchMutateIndispensably != nil {
		return b.postBatchMutateIndispensably(ctx, env, req)
	}
	return nil
}

// OnPostStartRegionOperation registers the PostStartRegionOperation callback.
func (b *RegionBuilder) OnPostStartRegionOperation(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostStartRegionOperationRequest) error) *RegionBuilder {
	b.postStartRegionOperation = fn
	return b
}

func (b *RegionBuilder) PostStartRegionOperation(ctx context.Context, env ObserverEnv, req *hookpb.PostStartRegionOperationRequest) error {
	if b.postStartRegionOperation != nil {
		return b.postStartRegionOperation(ctx, env, req)
	}
	return nil
}

// OnPostCloseRegionOperation registers the PostCloseRegionOperation callback.
func (b *RegionBuilder) OnPostCloseRegionOperation(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRegionOperationRequest) error) *RegionBuilder {
	b.postCloseRegionOperation = fn
	return b
}

func (b *RegionBuilder) PostCloseRegionOperation(ctx context.Context, env ObserverEnv, req *hookpb.PostCloseRegionOperationRequest) error {
	if b.postCloseRegionOperation != nil {
		return b.postCloseRegionOperation(ctx, env, req)
	}
	return nil
}

// OnPreCheckAndPut registers the PreCheckAndPut callback.
func (b *RegionBuilder) OnPreCheckAndPut(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndPut = fn
	return b
}

func (b *RegionBuilder) PreCheckAndPut(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutRequest) (HookResult, error) {
	if b.preCheckAndPut != nil {
		return b.preCheckAndPut(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCheckAndPut registers the PostCheckAndPut callback.
func (b *RegionBuilder) OnPostCheckAndPut(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndPutRequest) error) *RegionBuilder {
	b.postCheckAndPut = fn
	return b
}

func (b *RegionBuilder) PostCheckAndPut(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndPutRequest) error {
	if b.postCheckAndPut != nil {
		return b.postCheckAndPut(ctx, env, req)
	}
	return nil
}

// OnPreCheckAndPutAfterRowLock registers the PreCheckAndPutAfterRowLock callback.
func (b *RegionBuilder) OnPreCheckAndPutAfterRowLock(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutAfterRowLockRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndPutAfterRowLock = fn
	return b
}

func (b *RegionBuilder) PreCheckAndPutAfterRowLock(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndPutAfterRowLockRequest) (HookResult, error) {
	if b.preCheckAndPutAfterRowLock != nil {
		return b.preCheckAndPutAfterRowLock(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreCheckAndDelete registers the PreCheckAndDelete callback.
func (b *RegionBuilder) OnPreCheckAndDelete(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndDelete = fn
	return b
}

func (b *RegionBuilder) PreCheckAndDelete(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteRequest) (HookResult, error) {
	if b.preCheckAndDelete != nil {
		return b.preCheckAndDelete(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCheckAndDelete registers the PostCheckAndDelete callback.
func (b *RegionBuilder) OnPostCheckAndDelete(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndDeleteRequest) error) *RegionBuilder {
	b.postCheckAndDelete = fn
	return b
}

func (b *RegionBuilder) PostCheckAndDelete(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndDeleteRequest) error {
	if b.postCheckAndDelete != nil {
		return b.postCheckAndDelete(ctx, env, req)
	}
	return nil
}

// OnPreCheckAndDeleteAfterRowLock registers the PreCheckAndDeleteAfterRowLock callback.
func (b *RegionBuilder) OnPreCheckAndDeleteAfterRowLock(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteAfterRowLockRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndDeleteAfterRowLock = fn
	return b
}

func (b *RegionBuilder) PreCheckAndDeleteAfterRowLock(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndDeleteAfterRowLockRequest) (HookResult, error) {
	if b.preCheckAndDeleteAfterRowLock != nil {
		return b.preCheckAndDeleteAfterRowLock(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreCheckAndMutate registers the PreCheckAndMutate callback.
func (b *RegionBuilder) OnPreCheckAndMutate(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndMutate = fn
	return b
}

func (b *RegionBuilder) PreCheckAndMutate(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateRequest) (HookResult, error) {
	if b.preCheckAndMutate != nil {
		return b.preCheckAndMutate(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCheckAndMutate registers the PostCheckAndMutate callback.
func (b *RegionBuilder) OnPostCheckAndMutate(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndMutateRequest) error) *RegionBuilder {
	b.postCheckAndMutate = fn
	return b
}

func (b *RegionBuilder) PostCheckAndMutate(ctx context.Context, env ObserverEnv, req *hookpb.PostCheckAndMutateRequest) error {
	if b.postCheckAndMutate != nil {
		return b.postCheckAndMutate(ctx, env, req)
	}
	return nil
}

// OnPreCheckAndMutateAfterRowLock registers the PreCheckAndMutateAfterRowLock callback.
func (b *RegionBuilder) OnPreCheckAndMutateAfterRowLock(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateAfterRowLockRequest) (HookResult, error)) *RegionBuilder {
	b.preCheckAndMutateAfterRowLock = fn
	return b
}

func (b *RegionBuilder) PreCheckAndMutateAfterRowLock(ctx context.Context, env ObserverEnv, req *hookpb.PreCheckAndMutateAfterRowLockRequest) (HookResult, error) {
	if b.preCheckAndMutateAfterRowLock != nil {
		return b.preCheckAndMutateAfterRowLock(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreAppend registers the PreAppend callback.
func (b *RegionBuilder) OnPreAppend(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendRequest) (HookResult, error)) *RegionBuilder {
	b.preAppend = fn
	return b
}

func (b *RegionBuilder) PreAppend(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendRequest) (HookResult, error) {
	if b.preAppend != nil {
		return b.preAppend(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostAppend registers the PostAppend callback.
func (b *RegionBuilder) OnPostAppend(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendRequest) error) *RegionBuilder {
	b.postAppend = fn
	return b
}

func (b *RegionBuilder) PostAppend(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendRequest) error {
	if b.postAppend != nil {
		return b.postAppend(ctx, env, req)
	}
	return nil
}

// OnPreAppendAfterRowLock registers the PreAppendAfterRowLock callback.
func (b *RegionBuilder) OnPreAppendAfterRowLock(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendAfterRowLockRequest) (HookResult, error)) *RegionBuilder {
	b.preAppendAfterRowLock = fn
	return b
}

func (b *RegionBuilder) PreAppendAfterRowLock(ctx context.Context, env ObserverEnv, req *hookpb.PreAppendAfterRowLockRequest) (HookResult, error) {
	if b.preAppendAfterRowLock != nil {
		return b.preAppendAfterRowLock(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreIncrement registers the PreIncrement callback.
func (b *RegionBuilder) OnPreIncrement(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementRequest) (HookResult, error)) *RegionBuilder {
	b.preIncrement = fn
	return b
}

func (b *RegionBuilder) PreIncrement(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementRequest) (HookResult, error) {
	if b.preIncrement != nil {
		return b.preIncrement(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostIncrement registers the PostIncrement callback.
func (b *RegionBuilder) OnPostIncrement(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementRequest) error) *RegionBuilder {
	b.postIncrement = fn
	return b
}

func (b *RegionBuilder) PostIncrement(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementRequest) error {
	if b.postIncrement != nil {
		return b.postIncrement(ctx, env, req)
	}
	return nil
}

// OnPreIncrementAfterRowLock registers the PreIncrementAfterRowLock callback.
func (b *RegionBuilder) OnPreIncrementAfterRowLock(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementAfterRowLockRequest) (HookResult, error)) *RegionBuilder {
	b.preIncrementAfterRowLock = fn
	return b
}

func (b *RegionBuilder) PreIncrementAfterRowLock(ctx context.Context, env ObserverEnv, req *hookpb.PreIncrementAfterRowLockRequest) (HookResult, error) {
	if b.preIncrementAfterRowLock != nil {
		return b.preIncrementAfterRowLock(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreScannerOpen registers the PreScannerOpen callback.
func (b *RegionBuilder) OnPreScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preScannerOpen = fn
	return b
}

func (b *RegionBuilder) PreScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerOpenRequest) (HookResult, error) {
	if b.preScannerOpen != nil {
		return b.preScannerOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostScannerOpen registers the PostScannerOpen callback.
func (b *RegionBuilder) OnPostScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerOpenRequest) error) *RegionBuilder {
	b.postScannerOpen = fn
	return b
}

func (b *RegionBuilder) PostScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerOpenRequest) error {
	if b.postScannerOpen != nil {
		return b.postScannerOpen(ctx, env, req)
	}
	return nil
}

// OnPreScannerNext registers the PreScannerNext callback.
func (b *RegionBuilder) OnPreScannerNext(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerNextRequest) (HookResult, error)) *RegionBuilder {
	b.preScannerNext = fn
	return b
}

func (b *RegionBuilder) PreScannerNext(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerNextRequest) (HookResult, error) {
	if b.preScannerNext != nil {
		return b.preScannerNext(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostScannerNext registers the PostScannerNext callback.
func (b *RegionBuilder) OnPostScannerNext(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerNextRequest) error) *RegionBuilder {
	b.postScannerNext = fn
	return b
}

func (b *RegionBuilder) PostScannerNext(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerNextRequest) error {
	if b.postScannerNext != nil {
		return b.postScannerNext(ctx, env, req)
	}
	return nil
}

// OnPostScannerFilterRow registers the PostScannerFilterRow callback.
func (b *RegionBuilder) OnPostScannerFilterRow(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerFilterRowRequest) error) *RegionBuilder {
	b.postScannerFilterRow = fn
	return b
}

func (b *RegionBuilder) PostScannerFilterRow(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerFilterRowRequest) error {
	if b.postScannerFilterRow != nil {
		return b.postScannerFilterRow(ctx, env, req)
	}
	return nil
}

// OnPreScannerClose registers the PreScannerClose callback.
func (b *RegionBuilder) OnPreScannerClose(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerCloseRequest) (HookResult, error)) *RegionBuilder {
	b.preScannerClose = fn
	return b
}

func (b *RegionBuilder) PreScannerClose(ctx context.Context, env ObserverEnv, req *hookpb.PreScannerCloseRequest) (HookResult, error) {
	if b.preScannerClose != nil {
		return b.preScannerClose(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostScannerClose registers the PostScannerClose callback.
func (b *RegionBuilder) OnPostScannerClose(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerCloseRequest) error) *RegionBuilder {
	b.postScannerClose = fn
	return b
}

func (b *RegionBuilder) PostScannerClose(ctx context.Context, env ObserverEnv, req *hookpb.PostScannerCloseRequest) error {
	if b.postScannerClose != nil {
		return b.postScannerClose(ctx, env, req)
	}
	return nil
}

// OnPreStoreScannerOpen registers the PreStoreScannerOpen callback.
func (b *RegionBuilder) OnPreStoreScannerOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreScannerOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preStoreScannerOpen = fn
	return b
}

func (b *RegionBuilder) PreStoreScannerOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreScannerOpenRequest) (HookResult, error) {
	if b.preStoreScannerOpen != nil {
		return b.preStoreScannerOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPreReplayWALs registers the PreReplayWALs callback.
func (b *RegionBuilder) OnPreReplayWALs(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreReplayWALsRequest) (HookResult, error)) *RegionBuilder {
	b.preReplayWALs = fn
	return b
}

func (b *RegionBuilder) PreReplayWALs(ctx context.Context, env ObserverEnv, req *hookpb.PreReplayWALsRequest) (HookResult, error) {
	if b.preReplayWALs != nil {
		return b.preReplayWALs(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostReplayWALs registers the PostReplayWALs callback.
func (b *RegionBuilder) OnPostReplayWALs(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostReplayWALsRequest) error) *RegionBuilder {
	b.postReplayWALs = fn
	return b
}

func (b *RegionBuilder) PostReplayWALs(ctx context.Context, env ObserverEnv, req *hookpb.PostReplayWALsRequest) error {
	if b.postReplayWALs != nil {
		return b.postReplayWALs(ctx, env, req)
	}
	return nil
}

// OnPreWALRestore registers the PreWALRestore callback.
func (b *RegionBuilder) OnPreWALRestore(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreWALRestoreRequest) (HookResult, error)) *RegionBuilder {
	b.preWALRestore = fn
	return b
}

func (b *RegionBuilder) PreWALRestore(ctx context.Context, env ObserverEnv, req *hookpb.PreWALRestoreRequest) (HookResult, error) {
	if b.preWALRestore != nil {
		return b.preWALRestore(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostWALRestore registers the PostWALRestore callback.
func (b *RegionBuilder) OnPostWALRestore(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostWALRestoreRequest) error) *RegionBuilder {
	b.postWALRestore = fn
	return b
}

func (b *RegionBuilder) PostWALRestore(ctx context.Context, env ObserverEnv, req *hookpb.PostWALRestoreRequest) error {
	if b.postWALRestore != nil {
		return b.postWALRestore(ctx, env, req)
	}
	return nil
}

// OnPreBulkLoadHFile registers the PreBulkLoadHFile callback.
func (b *RegionBuilder) OnPreBulkLoadHFile(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreBulkLoadHFileRequest) (HookResult, error)) *RegionBuilder {
	b.preBulkLoadHFile = fn
	return b
}

func (b *RegionBuilder) PreBulkLoadHFile(ctx context.Context, env ObserverEnv, req *hookpb.PreBulkLoadHFileRequest) (HookResult, error) {
	if b.preBulkLoadHFile != nil {
		return b.preBulkLoadHFile(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostBulkLoadHFile registers the PostBulkLoadHFile callback.
func (b *RegionBuilder) OnPostBulkLoadHFile(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostBulkLoadHFileRequest) error) *RegionBuilder {
	b.postBulkLoadHFile = fn
	return b
}

func (b *RegionBuilder) PostBulkLoadHFile(ctx context.Context, env ObserverEnv, req *hookpb.PostBulkLoadHFileRequest) error {
	if b.postBulkLoadHFile != nil {
		return b.postBulkLoadHFile(ctx, env, req)
	}
	return nil
}

// OnPreCommitStoreFile registers the PreCommitStoreFile callback.
func (b *RegionBuilder) OnPreCommitStoreFile(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreCommitStoreFileRequest) (HookResult, error)) *RegionBuilder {
	b.preCommitStoreFile = fn
	return b
}

func (b *RegionBuilder) PreCommitStoreFile(ctx context.Context, env ObserverEnv, req *hookpb.PreCommitStoreFileRequest) (HookResult, error) {
	if b.preCommitStoreFile != nil {
		return b.preCommitStoreFile(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostCommitStoreFile registers the PostCommitStoreFile callback.
func (b *RegionBuilder) OnPostCommitStoreFile(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostCommitStoreFileRequest) error) *RegionBuilder {
	b.postCommitStoreFile = fn
	return b
}

func (b *RegionBuilder) PostCommitStoreFile(ctx context.Context, env ObserverEnv, req *hookpb.PostCommitStoreFileRequest) error {
	if b.postCommitStoreFile != nil {
		return b.postCommitStoreFile(ctx, env, req)
	}
	return nil
}

// OnPreStoreFileReaderOpen registers the PreStoreFileReaderOpen callback.
func (b *RegionBuilder) OnPreStoreFileReaderOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreFileReaderOpenRequest) (HookResult, error)) *RegionBuilder {
	b.preStoreFileReaderOpen = fn
	return b
}

func (b *RegionBuilder) PreStoreFileReaderOpen(ctx context.Context, env ObserverEnv, req *hookpb.PreStoreFileReaderOpenRequest) (HookResult, error) {
	if b.preStoreFileReaderOpen != nil {
		return b.preStoreFileReaderOpen(ctx, env, req)
	}
	return HookResult{}, nil
}

// OnPostStoreFileReaderOpen registers the PostStoreFileReaderOpen callback.
func (b *RegionBuilder) OnPostStoreFileReaderOpen(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostStoreFileReaderOpenRequest) error) *RegionBuilder {
	b.postStoreFileReaderOpen = fn
	return b
}

func (b *RegionBuilder) PostStoreFileReaderOpen(ctx context.Context, env ObserverEnv, req *hookpb.PostStoreFileReaderOpenRequest) error {
	if b.postStoreFileReaderOpen != nil {
		return b.postStoreFileReaderOpen(ctx, env, req)
	}
	return nil
}

// OnPostMutationBeforeWAL registers the PostMutationBeforeWAL callback.
func (b *RegionBuilder) OnPostMutationBeforeWAL(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostMutationBeforeWALRequest) error) *RegionBuilder {
	b.postMutationBeforeWAL = fn
	return b
}

func (b *RegionBuilder) PostMutationBeforeWAL(ctx context.Context, env ObserverEnv, req *hookpb.PostMutationBeforeWALRequest) error {
	if b.postMutationBeforeWAL != nil {
		return b.postMutationBeforeWAL(ctx, env, req)
	}
	return nil
}

// OnPostIncrementBeforeWAL registers the PostIncrementBeforeWAL callback.
func (b *RegionBuilder) OnPostIncrementBeforeWAL(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementBeforeWALRequest) error) *RegionBuilder {
	b.postIncrementBeforeWAL = fn
	return b
}

func (b *RegionBuilder) PostIncrementBeforeWAL(ctx context.Context, env ObserverEnv, req *hookpb.PostIncrementBeforeWALRequest) error {
	if b.postIncrementBeforeWAL != nil {
		return b.postIncrementBeforeWAL(ctx, env, req)
	}
	return nil
}

// OnPostAppendBeforeWAL registers the PostAppendBeforeWAL callback.
func (b *RegionBuilder) OnPostAppendBeforeWAL(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendBeforeWALRequest) error) *RegionBuilder {
	b.postAppendBeforeWAL = fn
	return b
}

func (b *RegionBuilder) PostAppendBeforeWAL(ctx context.Context, env ObserverEnv, req *hookpb.PostAppendBeforeWALRequest) error {
	if b.postAppendBeforeWAL != nil {
		return b.postAppendBeforeWAL(ctx, env, req)
	}
	return nil
}

// OnPostInstantiateDeleteTracker registers the PostInstantiateDeleteTracker callback.
func (b *RegionBuilder) OnPostInstantiateDeleteTracker(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PostInstantiateDeleteTrackerRequest) error) *RegionBuilder {
	b.postInstantiateDeleteTracker = fn
	return b
}

func (b *RegionBuilder) PostInstantiateDeleteTracker(ctx context.Context, env ObserverEnv, req *hookpb.PostInstantiateDeleteTrackerRequest) error {
	if b.postInstantiateDeleteTracker != nil {
		return b.postInstantiateDeleteTracker(ctx, env, req)
	}
	return nil
}

// OnPreWALAppend registers the PreWALAppend callback.
func (b *RegionBuilder) OnPreWALAppend(fn func(ctx context.Context, env ObserverEnv, req *hookpb.PreWALAppendRequest) (HookResult, error)) *RegionBuilder {
	b.preWALAppend = fn
	return b
}

func (b *RegionBuilder) PreWALAppend(ctx context.Context, env ObserverEnv, req *hookpb.PreWALAppendRequest) (HookResult, error) {
	if b.preWALAppend != nil {
		return b.preWALAppend(ctx, env, req)
	}
	return HookResult{}, nil
}
