// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen-wiretypes; DO NOT EDIT.

// Public aliases for the internal wire types the Observer interfaces use, so
// out-of-tree authors can name them. Regenerate: go generate ./pkg/hbasecop

package hbasecop

import (
	"github.com/virogg/go-hbase/internal/wire/hbasepb"
	"github.com/virogg/go-hbase/internal/wire/hookpb"
)

// Re-exported from github.com/virogg/go-hbase/internal/wire/hbasepb.
type Cell = hbasepb.Cell
type CellType = hbasepb.CellType
type Column = hbasepb.Column
type ColumnFamilyTimeRange = hbasepb.ColumnFamilyTimeRange
type Comparator = hbasepb.Comparator
type Consistency = hbasepb.Consistency
type Cursor = hbasepb.Cursor
type Filter = hbasepb.Filter
type Get = hbasepb.Get
type KeyValue = hbasepb.KeyValue
type MutationProto_ColumnValue = hbasepb.MutationProto_ColumnValue
type MutationProto_ColumnValue_QualifierValue = hbasepb.MutationProto_ColumnValue_QualifierValue
type MutationProto_DeleteType = hbasepb.MutationProto_DeleteType
type MutationProto_Durability = hbasepb.MutationProto_Durability
type MutationProto_MutationType = hbasepb.MutationProto_MutationType
type NameBytesPair = hbasepb.NameBytesPair
type RegionInfo = hbasepb.RegionInfo
type RegionSpecifier = hbasepb.RegionSpecifier
type RegionSpecifier_RegionSpecifierType = hbasepb.RegionSpecifier_RegionSpecifierType
type Result = hbasepb.Result
type Scan = hbasepb.Scan
type Scan_ReadType = hbasepb.Scan_ReadType
type ServerName = hbasepb.ServerName
type TableName = hbasepb.TableName
type TimeRange = hbasepb.TimeRange

// Re-exported from github.com/virogg/go-hbase/internal/wire/hookpb.
type BulkLoadFamilyPaths = hookpb.BulkLoadFamilyPaths
type CellPair = hookpb.CellPair
type CheckAndMutateAction = hookpb.CheckAndMutateAction
type CheckAndMutateResultProto = hookpb.CheckAndMutateResultProto
type CompactionRequestSummary = hookpb.CompactionRequestSummary
type FamilyPath = hookpb.FamilyPath
type HookContext = hookpb.HookContext
type MutationOperation = hookpb.MutationOperation
type PathPair = hookpb.PathPair
type PostAppendBeforeWALRequest = hookpb.PostAppendBeforeWALRequest
type PostAppendRequest = hookpb.PostAppendRequest
type PostAssignRequest = hookpb.PostAssignRequest
type PostBalanceRequest = hookpb.PostBalanceRequest
type PostBatchMutateIndispensablyRequest = hookpb.PostBatchMutateIndispensablyRequest
type PostBatchMutateRequest = hookpb.PostBatchMutateRequest
type PostBulkLoadHFileRequest = hookpb.PostBulkLoadHFileRequest
type PostCheckAndDeleteRequest = hookpb.PostCheckAndDeleteRequest
type PostCheckAndMutateRequest = hookpb.PostCheckAndMutateRequest
type PostCheckAndPutRequest = hookpb.PostCheckAndPutRequest
type PostClearCompactionQueuesRequest = hookpb.PostClearCompactionQueuesRequest
type PostCloseRegionOperationRequest = hookpb.PostCloseRegionOperationRequest
type PostCloseRequest = hookpb.PostCloseRequest
type PostCommitStoreFileRequest = hookpb.PostCommitStoreFileRequest
type PostCompactRequest = hookpb.PostCompactRequest
type PostCompactSelectionRequest = hookpb.PostCompactSelectionRequest
type PostCreateTableRequest = hookpb.PostCreateTableRequest
type PostDeleteRequest = hookpb.PostDeleteRequest
type PostDeleteTableRequest = hookpb.PostDeleteTableRequest
type PostDisableTableRequest = hookpb.PostDisableTableRequest
type PostEnableTableRequest = hookpb.PostEnableTableRequest
type PostExecuteProceduresRequest = hookpb.PostExecuteProceduresRequest
type PostExistsRequest = hookpb.PostExistsRequest
type PostFlushRequest = hookpb.PostFlushRequest
type PostGetOpRequest = hookpb.PostGetOpRequest
type PostIncrementBeforeWALRequest = hookpb.PostIncrementBeforeWALRequest
type PostIncrementRequest = hookpb.PostIncrementRequest
type PostInstantiateDeleteTrackerRequest = hookpb.PostInstantiateDeleteTrackerRequest
type PostMemStoreCompactionRequest = hookpb.PostMemStoreCompactionRequest
type PostModifyTableRequest = hookpb.PostModifyTableRequest
type PostMoveRequest = hookpb.PostMoveRequest
type PostMutationBeforeWALRequest = hookpb.PostMutationBeforeWALRequest
type PostOpenRequest = hookpb.PostOpenRequest
type PostPutRequest = hookpb.PostPutRequest
type PostReplayWALsRequest = hookpb.PostReplayWALsRequest
type PostReplicateLogEntriesRequest = hookpb.PostReplicateLogEntriesRequest
type PostRollWalWriterRequestRequest = hookpb.PostRollWalWriterRequestRequest
type PostScannerCloseRequest = hookpb.PostScannerCloseRequest
type PostScannerFilterRowRequest = hookpb.PostScannerFilterRowRequest
type PostScannerNextRequest = hookpb.PostScannerNextRequest
type PostScannerOpenRequest = hookpb.PostScannerOpenRequest
type PostStartRegionOperationRequest = hookpb.PostStartRegionOperationRequest
type PostStoreFileReaderOpenRequest = hookpb.PostStoreFileReaderOpenRequest
type PostTruncateTableRequest = hookpb.PostTruncateTableRequest
type PostUnassignRequest = hookpb.PostUnassignRequest
type PostWALRestoreRequest = hookpb.PostWALRestoreRequest
type PostWALRollRequest = hookpb.PostWALRollRequest
type PostWALWriteRequest = hookpb.PostWALWriteRequest
type PreAppendAfterRowLockRequest = hookpb.PreAppendAfterRowLockRequest
type PreAppendRequest = hookpb.PreAppendRequest
type PreAssignRequest = hookpb.PreAssignRequest
type PreBalanceRequest = hookpb.PreBalanceRequest
type PreBatchMutateRequest = hookpb.PreBatchMutateRequest
type PreBulkLoadHFileRequest = hookpb.PreBulkLoadHFileRequest
type PreCheckAndDeleteAfterRowLockRequest = hookpb.PreCheckAndDeleteAfterRowLockRequest
type PreCheckAndDeleteRequest = hookpb.PreCheckAndDeleteRequest
type PreCheckAndMutateAfterRowLockRequest = hookpb.PreCheckAndMutateAfterRowLockRequest
type PreCheckAndMutateRequest = hookpb.PreCheckAndMutateRequest
type PreCheckAndPutAfterRowLockRequest = hookpb.PreCheckAndPutAfterRowLockRequest
type PreCheckAndPutRequest = hookpb.PreCheckAndPutRequest
type PreCleanupBulkLoadRequest = hookpb.PreCleanupBulkLoadRequest
type PreClearCompactionQueuesRequest = hookpb.PreClearCompactionQueuesRequest
type PreCloseRequest = hookpb.PreCloseRequest
type PreCommitStoreFileRequest = hookpb.PreCommitStoreFileRequest
type PreCompactRequest = hookpb.PreCompactRequest
type PreCompactScannerOpenRequest = hookpb.PreCompactScannerOpenRequest
type PreCompactSelectionRequest = hookpb.PreCompactSelectionRequest
type PreCreateTableRequest = hookpb.PreCreateTableRequest
type PreDeleteRequest = hookpb.PreDeleteRequest
type PreDeleteTableRequest = hookpb.PreDeleteTableRequest
type PreDisableTableRequest = hookpb.PreDisableTableRequest
type PreEnableTableRequest = hookpb.PreEnableTableRequest
type PreExecuteProceduresRequest = hookpb.PreExecuteProceduresRequest
type PreExistsRequest = hookpb.PreExistsRequest
type PreFlushRequest = hookpb.PreFlushRequest
type PreFlushScannerOpenRequest = hookpb.PreFlushScannerOpenRequest
type PreGetOpRequest = hookpb.PreGetOpRequest
type PreIncrementAfterRowLockRequest = hookpb.PreIncrementAfterRowLockRequest
type PreIncrementRequest = hookpb.PreIncrementRequest
type PreMemStoreCompactionCompactRequest = hookpb.PreMemStoreCompactionCompactRequest
type PreMemStoreCompactionCompactScannerOpenRequest = hookpb.PreMemStoreCompactionCompactScannerOpenRequest
type PreMemStoreCompactionRequest = hookpb.PreMemStoreCompactionRequest
type PreModifyTableRequest = hookpb.PreModifyTableRequest
type PreMoveRequest = hookpb.PreMoveRequest
type PreOpenRequest = hookpb.PreOpenRequest
type PrePrepareBulkLoadRequest = hookpb.PrePrepareBulkLoadRequest
type PrePrepareTimeStampForDeleteVersionRequest = hookpb.PrePrepareTimeStampForDeleteVersionRequest
type PrePutRequest = hookpb.PrePutRequest
type PreReplayWALsRequest = hookpb.PreReplayWALsRequest
type PreReplicateLogEntriesRequest = hookpb.PreReplicateLogEntriesRequest
type PreRollWalWriterRequestRequest = hookpb.PreRollWalWriterRequestRequest
type PreScannerCloseRequest = hookpb.PreScannerCloseRequest
type PreScannerNextRequest = hookpb.PreScannerNextRequest
type PreScannerOpenRequest = hookpb.PreScannerOpenRequest
type PreStopRegionServerRequest = hookpb.PreStopRegionServerRequest
type PreStoreFileReaderOpenRequest = hookpb.PreStoreFileReaderOpenRequest
type PreStoreScannerOpenRequest = hookpb.PreStoreScannerOpenRequest
type PreTruncateTableRequest = hookpb.PreTruncateTableRequest
type PreUnassignRequest = hookpb.PreUnassignRequest
type PreWALAppendRequest = hookpb.PreWALAppendRequest
type PreWALRestoreRequest = hookpb.PreWALRestoreRequest
type PreWALRollRequest = hookpb.PreWALRollRequest
type PreWALWriteRequest = hookpb.PreWALWriteRequest
type ServerNameProto = hookpb.ServerNameProto
type StoreFilePathProto = hookpb.StoreFilePathProto
type WalEditProto = hookpb.WalEditProto
type WalKeyProto = hookpb.WalKeyProto
