// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Command gen-builder generates pkg/hbasecop/region_builder.go: a RegionBuilder
// that lets authors register per-hook closures (NewRegion().OnPrePut(fn)) in
// lieu of implementing the full RegionObserver interface. Derived from the
// interface in observer.go so it never drifts. Run via go generate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strings"
)

func main() {
	src := flag.String("src", "observer.go", "source file declaring the interface")
	iface := flag.String("iface", "RegionObserver", "interface to build for")
	out := flag.String("out", "region_builder.go", "output file")
	flag.Parse()

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, *src, nil, parser.ParseComments)
	if err != nil {
		fatalf("parse %s: %v", *src, err)
	}
	it := findInterface(f, *iface)
	if it == nil {
		fatalf("interface %s not found in %s", *iface, *src)
	}

	render := func(n ast.Node) string {
		var b bytes.Buffer
		if err := printer.Fprint(&b, fset, n); err != nil {
			fatalf("render: %v", err)
		}
		return b.String()
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen-builder; DO NOT EDIT.

// RegionBuilder registers per-hook callbacks instead of implementing the full
// %s interface. Regenerate: go generate ./pkg/hbasecop

package hbasecop

import (
	"context"

	"github.com/virogg/go-hbase/internal/wire/hookpb"
)

// RegionBuilder is a %s assembled from per-hook closures; unset hooks are
// no-ops. Build with NewRegion and the On* setters, then pass to Run.
type RegionBuilder struct {
	UnimplementedRegionObserver
`, *iface, *iface)

	type hook struct{ name, field, ftype, params, results, args string }
	var hooks []hook
	for _, m := range it.Methods.List {
		if len(m.Names) != 1 {
			continue
		}
		ft, ok := m.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		name := m.Names[0].Name
		ftype := render(ft) // "func(ctx context.Context, ...) (HookResult, error)"
		sig := strings.TrimPrefix(ftype, "func")
		results := ""
		if i := matchParen(sig); i >= 0 {
			results = strings.TrimSpace(sig[i+1:])
		}
		hooks = append(hooks, hook{
			name:    name,
			field:   lowerFirst(name),
			ftype:   ftype,
			params:  sig, // "(params) results"
			results: results,
			args:    paramNames(ft),
		})
	}

	for _, h := range hooks {
		fmt.Fprintf(&b, "\t%s %s\n", h.field, h.ftype)
	}
	fmt.Fprint(&b, "}\n\nvar _ RegionObserver = (*RegionBuilder)(nil)\n\n")
	fmt.Fprint(&b, "// NewRegion returns an empty RegionBuilder.\nfunc NewRegion() *RegionBuilder { return &RegionBuilder{} }\n")

	for _, h := range hooks {
		// On<Name> setter.
		fmt.Fprintf(&b, "\n// On%s registers the %s callback.\nfunc (b *RegionBuilder) On%s(fn %s) *RegionBuilder {\n\tb.%s = fn\n\treturn b\n}\n",
			h.name, h.name, h.name, h.ftype, h.field)
		// Hook method.
		zero := "return nil"
		if strings.Contains(h.results, ",") {
			zero = "return HookResult{}, nil"
		}
		fmt.Fprintf(&b, "\nfunc (b *RegionBuilder) %s%s {\n\tif b.%s != nil {\n\t\treturn b.%s(%s)\n\t}\n\t%s\n}\n",
			h.name, h.params, h.field, h.field, h.args, zero)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fatalf("gofmt: %v\n----\n%s", err, b.String())
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-builder: wrote %d hooks to %s\n", len(hooks), *out)
}

func findInterface(f *ast.File, name string) *ast.InterfaceType {
	var found *ast.InterfaceType
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != name {
			return true
		}
		if it, ok := ts.Type.(*ast.InterfaceType); ok {
			found = it
		}
		return false
	})
	return found
}

// paramNames returns the comma-joined parameter identifiers of ft.
func paramNames(ft *ast.FuncType) string {
	var names []string
	for i, p := range ft.Params.List {
		if len(p.Names) == 0 {
			names = append(names, fmt.Sprintf("arg%d", i))
			continue
		}
		for _, id := range p.Names {
			names = append(names, id.Name)
		}
	}
	return strings.Join(names, ", ")
}

// matchParen returns the index of the ')' closing the '(' at s[0], or -1.
func matchParen(s string) int {
	depth := 0
	for i, r := range s {
		switch r {
		case '(':
			depth++
		case ')':
			if depth--; depth == 0 {
				return i
			}
		}
	}
	return -1
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-builder: "+format+"\n", args...)
	os.Exit(1)
}
