// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Wire-level frame envelope for go-hbase IPC.
//
// Carries Request/Response/Heartbeat/Error/Shutdown/Log between the Java
// RegionServer-side adapter and the Go runtime over a shared-memory ring.
//
// Stability: alpha (v1). Header layout is frozen for Phase 1; payload
// messages may grow new fields but field numbers will not be reused.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: wire.proto

package wirepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log_Level int32

const (
	Log_LEVEL_UNSPECIFIED Log_Level = 0
	Log_DEBUG             Log_Level = 1
	Log_INFO              Log_Level = 2
	Log_WARN              Log_Level = 3
	Log_ERROR             Log_Level = 4
)

// Enum value maps for Log_Level.
var (
	Log_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
	}
	Log_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"DEBUG":             1,
		"INFO":              2,
		"WARN":              3,
		"ERROR":             4,
	}
)

func (x Log_Level) Enum() *Log_Level {
	p := new(Log_Level)
	*p = x
	return p
}

func (x Log_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (Log_Level) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x Log_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Log_Level.Descriptor instead.
func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{6, 0}
}

// FrameHeader is the routing metadata carried on every frame.
//
//	req_id      — caller-assigned request id; correlates Request↔Response
//	              (and Error responses). Heartbeats carry req_id=0.
//	region_id   — HBase region identifier for routing on the Go side.
//	              Always 0 in Phase 1 (single-region E2E); real values
//	              land in T61.
//	hook_id     — Observer-method discriminator (T41 hook table).
//	              0 means "no hook" (control frames: Heartbeat/Shutdown/Log).
//	chunk_idx   — 0-based index of this chunk in a multi-chunk message.
//	chunk_total — total number of chunks (>=1). =1 for single-chunk.
type FrameHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         uint64                 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	RegionId      uint32                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	HookId        uint32                 `protobuf:"varint,3,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	ChunkIdx      uint32                 `protobuf:"varint,4,opt,name=chunk_idx,json=chunkIdx,proto3" json:"chunk_idx,omitempty"`
	ChunkTotal    uint32                 `protobuf:"varint,5,opt,name=chunk_total,json=chunkTotal,proto3" json:"chunk_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameHeader) Reset() {
	*x = FrameHeader{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameHeader) ProtoMessage() {}

func (x *FrameHeader) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameHeader.ProtoReflect.Descriptor instead.
func (*FrameHeader) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *FrameHeader) GetReqId() uint64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *FrameHeader) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *FrameHeader) GetHookId() uint32 {
	if x != nil {
		return x.HookId
	}
	return 0
}

func (x *FrameHeader) GetChunkIdx() uint32 {
	if x != nil {
		return x.ChunkIdx
	}
	return 0
}

func (x *FrameHeader) GetChunkTotal() uint32 {
	if x != nil {
		return x.ChunkTotal
	}
	return 0
}

// Request carries the PB-encoded HookContext (typed by FrameHeader.hook_id).
// Per-hook context shapes land in T22+ when HBase .proto is vendored.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookCtx       []byte                 `protobuf:"bytes,1,opt,name=hook_ctx,json=hookCtx,proto3" json:"hook_ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetHookCtx() []byte {
	if x != nil {
		return x.HookCtx
	}
	return nil
}

// Response carries the PB-encoded HookResponse, or is empty for void hooks.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookResp      []byte                 `protobuf:"bytes,1,opt,name=hook_resp,json=hookResp,proto3" json:"hook_resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetHookResp() []byte {
	if x != nil {
		return x.HookResp
	}
	return nil
}

// Heartbeat is emitted by the Go runtime on a fixed cadence; supervisor
// uses it for liveness (T33 watchdog). Header.req_id=0 by convention.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sender monotonic clock reading in nanoseconds.
	MonotonicNanos uint64 `protobuf:"varint,1,opt,name=monotonic_nanos,json=monotonicNanos,proto3" json:"monotonic_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetMonotonicNanos() uint64 {
	if x != nil {
		return x.MonotonicNanos
	}
	return 0
}

// Error replaces Response when a hook invocation fails on the Go side.
// Final routing (strict vs best-effort) is T32.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric class of the failure. 0 reserved for "unspecified".
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable detail; surfaced in IOException message in strict mode.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Shutdown is the Java-side signal to drain and exit.
type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{5}
}

func (x *Shutdown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Log is a structured log line forwarded from the Go runtime to the Java
// supervisor; supervisor relays to the HBase log subsystem.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Log_Level              `protobuf:"varint,1,opt,name=level,proto3,enum=virogg.hbasecop.v1.Log_Level" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetLevel() Log_Level {
	if x != nil {
		return x.Level
	}
	return Log_LEVEL_UNSPECIFIED
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Frame is the wire envelope. Every frame on the ring carries a header
// and exactly one payload.
type Frame struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *FrameHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Request
	//	*Frame_Response
	//	*Frame_Heartbeat
	//	*Frame_Error
	//	*Frame_Shutdown
	//	*Frame_Log
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{7}
}

func (x *Frame) GetHeader() *FrameHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Frame) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Frame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Frame) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Frame) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *Frame) GetLog() *Log {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type Frame_Response struct {
	Response *Response `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

type Frame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type Frame_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type Frame_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

type Frame_Log struct {
	Log *Log `protobuf:"bytes,7,opt,name=log,proto3,oneof"`
}

func (*Frame_Request) isFrame_Payload() {}

func (*Frame_Response) isFrame_Payload() {}

func (*Frame_Heartbeat) isFrame_Payload() {}

func (*Frame_Error) isFrame_Payload() {}

func (*Frame_Shutdown) isFrame_Payload() {}

func (*Frame_Log) isFrame_Payload() {}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\x12virogg.hbasecop.v1\"\x98\x01\n" +
	"\vFrameHeader\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\x04R\x05reqId\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\rR\bregionId\x12\x17\n" +
	"\ahook_id\x18\x03 \x01(\rR\x06hookId\x12\x1b\n" +
	"\tchunk_idx\x18\x04 \x01(\rR\bchunkIdx\x12\x1f\n" +
	"\vchunk_total\x18\x05 \x01(\rR\n" +
	"chunkTotal\"$\n" +
	"\aRequest\x12\x19\n" +
	"\bhook_ctx\x18\x01 \x01(\fR\ahookCtx\"'\n" +
	"\bResponse\x12\x1b\n" +
	"\thook_resp\x18\x01 \x01(\fR\bhookResp\"4\n" +
	"\tHeartbeat\x12'\n" +
	"\x0fmonotonic_nanos\x18\x01 \x01(\x04R\x0emonotonicNanos\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\bShutdown\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x9e\x01\n" +
	"\x03Log\x123\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1d.virogg.hbasecop.v1.Log.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\"\x9b\x03\n" +
	"\x05Frame\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.virogg.hbasecop.v1.FrameHeaderR\x06header\x127\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.virogg.hbasecop.v1.RequestH\x00R\arequest\x12:\n" +
	"\bresponse\x18\x03 \x01(\v2\x1c.virogg.hbasecop.v1.ResponseH\x00R\bresponse\x12=\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1d.virogg.hbasecop.v1.HeartbeatH\x00R\theartbeat\x121\n" +
	"\x05error\x18\x05 \x01(\v2\x19.virogg.hbasecop.v1.ErrorH\x00R\x05error\x12:\n" +
	"\bshutdown\x18\x06 \x01(\v2\x1c.virogg.hbasecop.v1.ShutdownH\x00R\bshutdown\x12+\n" +
	"\x03log\x18\a \x01(\v2\x17.virogg.hbasecop.v1.LogH\x00R\x03logB\t\n" +
	"\apayloadBb\n" +
	"\"com.virogg.hbasecop.bridge.wire.pbB\tWireProtoP\x01Z/github.com/virogg/go-hbase/internal/wire/wirepbb\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wire_proto_goTypes = []any{
	(Log_Level)(0),      // 0: virogg.hbasecop.v1.Log.Level
	(*FrameHeader)(nil), // 1: virogg.hbasecop.v1.FrameHeader
	(*Request)(nil),     // 2: virogg.hbasecop.v1.Request
	(*Response)(nil),    // 3: virogg.hbasecop.v1.Response
	(*Heartbeat)(nil),   // 4: virogg.hbasecop.v1.Heartbeat
	(*Error)(nil),       // 5: virogg.hbasecop.v1.Error
	(*Shutdown)(nil),    // 6: virogg.hbasecop.v1.Shutdown
	(*Log)(nil),         // 7: virogg.hbasecop.v1.Log
	(*Frame)(nil),       // 8: virogg.hbasecop.v1.Frame
}
var file_wire_proto_depIdxs = []int32{
	0, // 0: virogg.hbasecop.v1.Log.level:type_name -> virogg.hbasecop.v1.Log.Level
	1, // 1: virogg.hbasecop.v1.Frame.header:type_name -> virogg.hbasecop.v1.FrameHeader
	2, // 2: virogg.hbasecop.v1.Frame.request:type_name -> virogg.hbasecop.v1.Request
	3, // 3: virogg.hbasecop.v1.Frame.response:type_name -> virogg.hbasecop.v1.Response
	4, // 4: virogg.hbasecop.v1.Frame.heartbeat:type_name -> virogg.hbasecop.v1.Heartbeat
	5, // 5: virogg.hbasecop.v1.Frame.error:type_name -> virogg.hbasecop.v1.Error
	6, // 6: virogg.hbasecop.v1.Frame.shutdown:type_name -> virogg.hbasecop.v1.Shutdown
	7, // 7: virogg.hbasecop.v1.Frame.log:type_name -> virogg.hbasecop.v1.Log
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	file_wire_proto_msgTypes[7].OneofWrappers = []any{
		(*Frame_Request)(nil),
		(*Frame_Response)(nil),
		(*Frame_Heartbeat)(nil),
		(*Frame_Error)(nil),
		(*Frame_Shutdown)(nil),
		(*Frame_Log)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
