// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Command gen-wiretypes generates pkg/hbasecop/wiretypes.go: type aliases
// re-exporting the internal wire message/enum types so out-of-tree coprocessor
// authors can name the per-hook request envelopes their Observer methods are
// signed against. Aliases every exported type except SDK-built transport types
// and MutationProto (hand-aliased in observer.go). Run via go generate.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// pkgSpec describes one source wire package to harvest aliases from.
type pkgSpec struct {
	dir     string
	imp     string
	name    string
	exclude map[string]bool
}

// wireAlias is one emitted `type local = pkg.name` declaration.
type wireAlias struct {
	local string
	pkg   string
	imp   string
	name  string
}

func main() {
	hookpbDir := flag.String("hookpb", "../../internal/wire/hookpb", "dir of the generated hookpb package")
	hbasepbDir := flag.String("hbasepb", "../../internal/wire/hbasepb", "dir of the generated hbasepb package")
	out := flag.String("out", "wiretypes.go", "output file (in the hbasecop package dir)")
	flag.Parse()

	specs := []pkgSpec{
		{
			dir:     *hbasepbDir,
			imp:     "github.com/virogg/go-hbase/internal/wire/hbasepb",
			name:    "hbasepb",
			exclude: map[string]bool{"MutationProto": true},
		},
		{
			dir:     *hookpbDir,
			imp:     "github.com/virogg/go-hbase/internal/wire/hookpb",
			name:    "hookpb",
			exclude: map[string]bool{"HookId": true, "HookError": true, "HookResponse": true},
		},
	}

	var aliases []wireAlias
	seen := map[string]string{}
	for _, s := range specs {
		names, err := exportedTypeNames(s.dir)
		if err != nil {
			fatalf("scan %s: %v", s.dir, err)
		}
		for _, n := range names {
			if s.exclude[n] {
				continue
			}
			if prev, dup := seen[n]; dup {
				fatalf("alias name collision: %q exported by both %s and %s; extend the exclude policy", n, prev, s.name)
			}
			seen[n] = s.name
			aliases = append(aliases, wireAlias{local: n, pkg: s.name, imp: s.imp, name: n})
		}
	}
	sort.Slice(aliases, func(i, j int) bool {
		if aliases[i].pkg != aliases[j].pkg {
			return aliases[i].pkg < aliases[j].pkg
		}
		return aliases[i].local < aliases[j].local
	})

	var b bytes.Buffer
	fmt.Fprint(&b, `// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen-wiretypes; DO NOT EDIT.

// Public aliases for the internal wire types the Observer interfaces use, so
// out-of-tree authors can name them. Regenerate: go generate ./pkg/hbasecop

package hbasecop

import (
	"github.com/virogg/go-hbase/internal/wire/hbasepb"
	"github.com/virogg/go-hbase/internal/wire/hookpb"
)

`)
	lastPkg := ""
	for _, a := range aliases {
		if a.pkg != lastPkg {
			if lastPkg != "" {
				b.WriteByte('\n')
			}
			fmt.Fprintf(&b, "// Re-exported from %s.\n", a.imp)
			lastPkg = a.pkg
		}
		fmt.Fprintf(&b, "type %s = %s.%s\n", a.local, a.pkg, a.name)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fatalf("gofmt generated source: %v\n----\n%s", err, b.String())
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatalf("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "gen-wiretypes: wrote %d aliases to %s\n", len(aliases), *out)
}

func exportedTypeNames(dir string) ([]string, error) {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			return nil, err
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || !ts.Name.IsExported() {
					continue
				}
				names = append(names, ts.Name.Name)
			}
		}
	}
	return names, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-wiretypes: "+format+"\n", args...)
	os.Exit(1)
}
