// Copyright 2026 The go-hbase Authors
// SPDX-License-Identifier: Apache-2.0

// Per-hook request/response messages for HBase Observer coprocessors.
//
// One message pair per Observer method (PrePut/PostPut/PreGet/...). The
// concrete fields land in T21+ once HBase .proto types are vendored under
// proto/hbase/. For Phase 1 these are intentionally empty placeholders so
// that round-trip codegen on both sides is exercised end-to-end.
//
// Stability: alpha.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hooks.proto

package hookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HookContext is the shared per-call context (env, table descriptor refs,
// caller identity, ...). T22 fills it in once we vendor HBase types.
type HookContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookContext) Reset() {
	*x = HookContext{}
	mi := &file_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookContext) ProtoMessage() {}

func (x *HookContext) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookContext.ProtoReflect.Descriptor instead.
func (*HookContext) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{0}
}

// HookResponse is the shared per-call response envelope (mutations to
// re-emit, abort flag, ...). T22 fills it in.
type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_hooks_proto_rawDescGZIP(), []int{1}
}

var File_hooks_proto protoreflect.FileDescriptor

const file_hooks_proto_rawDesc = "" +
	"\n" +
	"\vhooks.proto\x12\x12virogg.hbasecop.v1\"\r\n" +
	"\vHookContext\"\x0e\n" +
	"\fHookResponseBc\n" +
	"\"com.virogg.hbasecop.bridge.wire.pbB\n" +
	"HooksProtoP\x01Z/github.com/virogg/go-hbase/internal/wire/hookpbb\x06proto3"

var (
	file_hooks_proto_rawDescOnce sync.Once
	file_hooks_proto_rawDescData []byte
)

func file_hooks_proto_rawDescGZIP() []byte {
	file_hooks_proto_rawDescOnce.Do(func() {
		file_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hooks_proto_rawDesc), len(file_hooks_proto_rawDesc)))
	})
	return file_hooks_proto_rawDescData
}

var file_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hooks_proto_goTypes = []any{
	(*HookContext)(nil),  // 0: virogg.hbasecop.v1.HookContext
	(*HookResponse)(nil), // 1: virogg.hbasecop.v1.HookResponse
}
var file_hooks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hooks_proto_init() }
func file_hooks_proto_init() {
	if File_hooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hooks_proto_rawDesc), len(file_hooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hooks_proto_goTypes,
		DependencyIndexes: file_hooks_proto_depIdxs,
		MessageInfos:      file_hooks_proto_msgTypes,
	}.Build()
	File_hooks_proto = out.File
	file_hooks_proto_goTypes = nil
	file_hooks_proto_depIdxs = nil
}
