// SPDX-License-Identifier: Apache-2.0
//
// Vendored from apache/hbase rel/2.5.10 — see proto/hbase/UPSTREAM.md.
// Slim subset: MutationProto only (with its nested Column/ColumnValue/
// QualifierValue/Durability/MutationType/DeleteType). Get, Result, Scan
// and the request/response envelopes will be added by T43+ when the
// read-path hooks land.

//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file contains protocol buffers that are used for Client service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hbase/Client.proto

package hbasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MutationProto_Durability int32

const (
	MutationProto_USE_DEFAULT MutationProto_Durability = 0
	MutationProto_SKIP_WAL    MutationProto_Durability = 1
	MutationProto_ASYNC_WAL   MutationProto_Durability = 2
	MutationProto_SYNC_WAL    MutationProto_Durability = 3
	MutationProto_FSYNC_WAL   MutationProto_Durability = 4
)

// Enum value maps for MutationProto_Durability.
var (
	MutationProto_Durability_name = map[int32]string{
		0: "USE_DEFAULT",
		1: "SKIP_WAL",
		2: "ASYNC_WAL",
		3: "SYNC_WAL",
		4: "FSYNC_WAL",
	}
	MutationProto_Durability_value = map[string]int32{
		"USE_DEFAULT": 0,
		"SKIP_WAL":    1,
		"ASYNC_WAL":   2,
		"SYNC_WAL":    3,
		"FSYNC_WAL":   4,
	}
)

func (x MutationProto_Durability) Enum() *MutationProto_Durability {
	p := new(MutationProto_Durability)
	*p = x
	return p
}

func (x MutationProto_Durability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationProto_Durability) Descriptor() protoreflect.EnumDescriptor {
	return file_hbase_Client_proto_enumTypes[0].Descriptor()
}

func (MutationProto_Durability) Type() protoreflect.EnumType {
	return &file_hbase_Client_proto_enumTypes[0]
}

func (x MutationProto_Durability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MutationProto_Durability) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MutationProto_Durability(num)
	return nil
}

// Deprecated: Use MutationProto_Durability.Descriptor instead.
func (MutationProto_Durability) EnumDescriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0, 0}
}

type MutationProto_MutationType int32

const (
	MutationProto_APPEND    MutationProto_MutationType = 0
	MutationProto_INCREMENT MutationProto_MutationType = 1
	MutationProto_PUT       MutationProto_MutationType = 2
	MutationProto_DELETE    MutationProto_MutationType = 3
)

// Enum value maps for MutationProto_MutationType.
var (
	MutationProto_MutationType_name = map[int32]string{
		0: "APPEND",
		1: "INCREMENT",
		2: "PUT",
		3: "DELETE",
	}
	MutationProto_MutationType_value = map[string]int32{
		"APPEND":    0,
		"INCREMENT": 1,
		"PUT":       2,
		"DELETE":    3,
	}
)

func (x MutationProto_MutationType) Enum() *MutationProto_MutationType {
	p := new(MutationProto_MutationType)
	*p = x
	return p
}

func (x MutationProto_MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationProto_MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_hbase_Client_proto_enumTypes[1].Descriptor()
}

func (MutationProto_MutationType) Type() protoreflect.EnumType {
	return &file_hbase_Client_proto_enumTypes[1]
}

func (x MutationProto_MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MutationProto_MutationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MutationProto_MutationType(num)
	return nil
}

// Deprecated: Use MutationProto_MutationType.Descriptor instead.
func (MutationProto_MutationType) EnumDescriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0, 1}
}

type MutationProto_DeleteType int32

const (
	MutationProto_DELETE_ONE_VERSION       MutationProto_DeleteType = 0
	MutationProto_DELETE_MULTIPLE_VERSIONS MutationProto_DeleteType = 1
	MutationProto_DELETE_FAMILY            MutationProto_DeleteType = 2
	MutationProto_DELETE_FAMILY_VERSION    MutationProto_DeleteType = 3
)

// Enum value maps for MutationProto_DeleteType.
var (
	MutationProto_DeleteType_name = map[int32]string{
		0: "DELETE_ONE_VERSION",
		1: "DELETE_MULTIPLE_VERSIONS",
		2: "DELETE_FAMILY",
		3: "DELETE_FAMILY_VERSION",
	}
	MutationProto_DeleteType_value = map[string]int32{
		"DELETE_ONE_VERSION":       0,
		"DELETE_MULTIPLE_VERSIONS": 1,
		"DELETE_FAMILY":            2,
		"DELETE_FAMILY_VERSION":    3,
	}
)

func (x MutationProto_DeleteType) Enum() *MutationProto_DeleteType {
	p := new(MutationProto_DeleteType)
	*p = x
	return p
}

func (x MutationProto_DeleteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationProto_DeleteType) Descriptor() protoreflect.EnumDescriptor {
	return file_hbase_Client_proto_enumTypes[2].Descriptor()
}

func (MutationProto_DeleteType) Type() protoreflect.EnumType {
	return &file_hbase_Client_proto_enumTypes[2]
}

func (x MutationProto_DeleteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MutationProto_DeleteType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MutationProto_DeleteType(num)
	return nil
}

// Deprecated: Use MutationProto_DeleteType.Descriptor instead.
func (MutationProto_DeleteType) EnumDescriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0, 2}
}

// *
// A specific Mutate operation. The Mutation is wrapped in MutationProto.
//
// The 'cell' field is deliberately left out of this slim vendor — HBase
// passes Cells out-of-band when associated_cell_count > 0; the in-band
// column_value path covers everything Phase 2 (T22+) needs.
type MutationProto struct {
	state       protoimpl.MessageState       `protogen:"open.v1"`
	Row         []byte                       `protobuf:"bytes,1,opt,name=row" json:"row,omitempty"`
	MutateType  *MutationProto_MutationType  `protobuf:"varint,2,opt,name=mutate_type,json=mutateType,enum=virogg.hbasecop.hbase.v1.MutationProto_MutationType" json:"mutate_type,omitempty"`
	ColumnValue []*MutationProto_ColumnValue `protobuf:"bytes,3,rep,name=column_value,json=columnValue" json:"column_value,omitempty"`
	Timestamp   *uint64                      `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Attribute   []*NameBytesPair             `protobuf:"bytes,5,rep,name=attribute" json:"attribute,omitempty"`
	Durability  *MutationProto_Durability    `protobuf:"varint,6,opt,name=durability,enum=virogg.hbasecop.hbase.v1.MutationProto_Durability,def=0" json:"durability,omitempty"`
	// For some mutations, a result may be returned, in which case,
	// time range can be specified for potential performance gain
	TimeRange *TimeRange `protobuf:"bytes,7,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	// The below count is set when the associated cells are NOT
	// part of this protobuf message; they are passed alongside
	// and then this Message is a placeholder with metadata.  The
	// count is needed to know how many to peel off the block of Cells as
	// ours.  NOTE: This is different from the pb managed cell_count of the
	// 'cell' field above which is non-null when the cells are pb'd.
	AssociatedCellCount *int32  `protobuf:"varint,8,opt,name=associated_cell_count,json=associatedCellCount" json:"associated_cell_count,omitempty"`
	Nonce               *uint64 `protobuf:"varint,9,opt,name=nonce" json:"nonce,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for MutationProto fields.
const (
	Default_MutationProto_Durability = MutationProto_USE_DEFAULT
)

func (x *MutationProto) Reset() {
	*x = MutationProto{}
	mi := &file_hbase_Client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationProto) ProtoMessage() {}

func (x *MutationProto) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_Client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationProto.ProtoReflect.Descriptor instead.
func (*MutationProto) Descriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0}
}

func (x *MutationProto) GetRow() []byte {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *MutationProto) GetMutateType() MutationProto_MutationType {
	if x != nil && x.MutateType != nil {
		return *x.MutateType
	}
	return MutationProto_APPEND
}

func (x *MutationProto) GetColumnValue() []*MutationProto_ColumnValue {
	if x != nil {
		return x.ColumnValue
	}
	return nil
}

func (x *MutationProto) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *MutationProto) GetAttribute() []*NameBytesPair {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *MutationProto) GetDurability() MutationProto_Durability {
	if x != nil && x.Durability != nil {
		return *x.Durability
	}
	return Default_MutationProto_Durability
}

func (x *MutationProto) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *MutationProto) GetAssociatedCellCount() int32 {
	if x != nil && x.AssociatedCellCount != nil {
		return *x.AssociatedCellCount
	}
	return 0
}

func (x *MutationProto) GetNonce() uint64 {
	if x != nil && x.Nonce != nil {
		return *x.Nonce
	}
	return 0
}

type MutationProto_ColumnValue struct {
	state          protoimpl.MessageState                      `protogen:"open.v1"`
	Family         []byte                                      `protobuf:"bytes,1,req,name=family" json:"family,omitempty"`
	QualifierValue []*MutationProto_ColumnValue_QualifierValue `protobuf:"bytes,2,rep,name=qualifier_value,json=qualifierValue" json:"qualifier_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutationProto_ColumnValue) Reset() {
	*x = MutationProto_ColumnValue{}
	mi := &file_hbase_Client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationProto_ColumnValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationProto_ColumnValue) ProtoMessage() {}

func (x *MutationProto_ColumnValue) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_Client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationProto_ColumnValue.ProtoReflect.Descriptor instead.
func (*MutationProto_ColumnValue) Descriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MutationProto_ColumnValue) GetFamily() []byte {
	if x != nil {
		return x.Family
	}
	return nil
}

func (x *MutationProto_ColumnValue) GetQualifierValue() []*MutationProto_ColumnValue_QualifierValue {
	if x != nil {
		return x.QualifierValue
	}
	return nil
}

type MutationProto_ColumnValue_QualifierValue struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Qualifier     []byte                    `protobuf:"bytes,1,opt,name=qualifier" json:"qualifier,omitempty"`
	Value         []byte                    `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Timestamp     *uint64                   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	DeleteType    *MutationProto_DeleteType `protobuf:"varint,4,opt,name=delete_type,json=deleteType,enum=virogg.hbasecop.hbase.v1.MutationProto_DeleteType" json:"delete_type,omitempty"`
	Tags          []byte                    `protobuf:"bytes,5,opt,name=tags" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationProto_ColumnValue_QualifierValue) Reset() {
	*x = MutationProto_ColumnValue_QualifierValue{}
	mi := &file_hbase_Client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationProto_ColumnValue_QualifierValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationProto_ColumnValue_QualifierValue) ProtoMessage() {}

func (x *MutationProto_ColumnValue_QualifierValue) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_Client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationProto_ColumnValue_QualifierValue.ProtoReflect.Descriptor instead.
func (*MutationProto_ColumnValue_QualifierValue) Descriptor() ([]byte, []int) {
	return file_hbase_Client_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *MutationProto_ColumnValue_QualifierValue) GetQualifier() []byte {
	if x != nil {
		return x.Qualifier
	}
	return nil
}

func (x *MutationProto_ColumnValue_QualifierValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MutationProto_ColumnValue_QualifierValue) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *MutationProto_ColumnValue_QualifierValue) GetDeleteType() MutationProto_DeleteType {
	if x != nil && x.DeleteType != nil {
		return *x.DeleteType
	}
	return MutationProto_DELETE_ONE_VERSION
}

func (x *MutationProto_ColumnValue_QualifierValue) GetTags() []byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_hbase_Client_proto protoreflect.FileDescriptor

const file_hbase_Client_proto_rawDesc = "" +
	"\n" +
	"\x12hbase/Client.proto\x12\x18virogg.hbasecop.hbase.v1\x1a\x11hbase/HBase.proto\"\x92\t\n" +
	"\rMutationProto\x12\x10\n" +
	"\x03row\x18\x01 \x01(\fR\x03row\x12U\n" +
	"\vmutate_type\x18\x02 \x01(\x0e24.virogg.hbasecop.hbase.v1.MutationProto.MutationTypeR\n" +
	"mutateType\x12V\n" +
	"\fcolumn_value\x18\x03 \x03(\v23.virogg.hbasecop.hbase.v1.MutationProto.ColumnValueR\vcolumnValue\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12E\n" +
	"\tattribute\x18\x05 \x03(\v2'.virogg.hbasecop.hbase.v1.NameBytesPairR\tattribute\x12_\n" +
	"\n" +
	"durability\x18\x06 \x01(\x0e22.virogg.hbasecop.hbase.v1.MutationProto.Durability:\vUSE_DEFAULTR\n" +
	"durability\x12B\n" +
	"\n" +
	"time_range\x18\a \x01(\v2#.virogg.hbasecop.hbase.v1.TimeRangeR\ttimeRange\x122\n" +
	"\x15associated_cell_count\x18\b \x01(\x05R\x13associatedCellCount\x12\x14\n" +
	"\x05nonce\x18\t \x01(\x04R\x05nonce\x1a\xe0\x02\n" +
	"\vColumnValue\x12\x16\n" +
	"\x06family\x18\x01 \x02(\fR\x06family\x12k\n" +
	"\x0fqualifier_value\x18\x02 \x03(\v2B.virogg.hbasecop.hbase.v1.MutationProto.ColumnValue.QualifierValueR\x0equalifierValue\x1a\xcb\x01\n" +
	"\x0eQualifierValue\x12\x1c\n" +
	"\tqualifier\x18\x01 \x01(\fR\tqualifier\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12S\n" +
	"\vdelete_type\x18\x04 \x01(\x0e22.virogg.hbasecop.hbase.v1.MutationProto.DeleteTypeR\n" +
	"deleteType\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\fR\x04tags\"W\n" +
	"\n" +
	"Durability\x12\x0f\n" +
	"\vUSE_DEFAULT\x10\x00\x12\f\n" +
	"\bSKIP_WAL\x10\x01\x12\r\n" +
	"\tASYNC_WAL\x10\x02\x12\f\n" +
	"\bSYNC_WAL\x10\x03\x12\r\n" +
	"\tFSYNC_WAL\x10\x04\">\n" +
	"\fMutationType\x12\n" +
	"\n" +
	"\x06APPEND\x10\x00\x12\r\n" +
	"\tINCREMENT\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\"p\n" +
	"\n" +
	"DeleteType\x12\x16\n" +
	"\x12DELETE_ONE_VERSION\x10\x00\x12\x1c\n" +
	"\x18DELETE_MULTIPLE_VERSIONS\x10\x01\x12\x11\n" +
	"\rDELETE_FAMILY\x10\x02\x12\x19\n" +
	"\x15DELETE_FAMILY_VERSION\x10\x03Bc\n" +
	"\x1ccom.virogg.hbasecop.hbase.v1B\fClientProtosH\x01Z0github.com/virogg/go-hbase/internal/wire/hbasepb\xa0\x01\x01"

var (
	file_hbase_Client_proto_rawDescOnce sync.Once
	file_hbase_Client_proto_rawDescData []byte
)

func file_hbase_Client_proto_rawDescGZIP() []byte {
	file_hbase_Client_proto_rawDescOnce.Do(func() {
		file_hbase_Client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hbase_Client_proto_rawDesc), len(file_hbase_Client_proto_rawDesc)))
	})
	return file_hbase_Client_proto_rawDescData
}

var file_hbase_Client_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_hbase_Client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hbase_Client_proto_goTypes = []any{
	(MutationProto_Durability)(0),                    // 0: virogg.hbasecop.hbase.v1.MutationProto.Durability
	(MutationProto_MutationType)(0),                  // 1: virogg.hbasecop.hbase.v1.MutationProto.MutationType
	(MutationProto_DeleteType)(0),                    // 2: virogg.hbasecop.hbase.v1.MutationProto.DeleteType
	(*MutationProto)(nil),                            // 3: virogg.hbasecop.hbase.v1.MutationProto
	(*MutationProto_ColumnValue)(nil),                // 4: virogg.hbasecop.hbase.v1.MutationProto.ColumnValue
	(*MutationProto_ColumnValue_QualifierValue)(nil), // 5: virogg.hbasecop.hbase.v1.MutationProto.ColumnValue.QualifierValue
	(*NameBytesPair)(nil),                            // 6: virogg.hbasecop.hbase.v1.NameBytesPair
	(*TimeRange)(nil),                                // 7: virogg.hbasecop.hbase.v1.TimeRange
}
var file_hbase_Client_proto_depIdxs = []int32{
	1, // 0: virogg.hbasecop.hbase.v1.MutationProto.mutate_type:type_name -> virogg.hbasecop.hbase.v1.MutationProto.MutationType
	4, // 1: virogg.hbasecop.hbase.v1.MutationProto.column_value:type_name -> virogg.hbasecop.hbase.v1.MutationProto.ColumnValue
	6, // 2: virogg.hbasecop.hbase.v1.MutationProto.attribute:type_name -> virogg.hbasecop.hbase.v1.NameBytesPair
	0, // 3: virogg.hbasecop.hbase.v1.MutationProto.durability:type_name -> virogg.hbasecop.hbase.v1.MutationProto.Durability
	7, // 4: virogg.hbasecop.hbase.v1.MutationProto.time_range:type_name -> virogg.hbasecop.hbase.v1.TimeRange
	5, // 5: virogg.hbasecop.hbase.v1.MutationProto.ColumnValue.qualifier_value:type_name -> virogg.hbasecop.hbase.v1.MutationProto.ColumnValue.QualifierValue
	2, // 6: virogg.hbasecop.hbase.v1.MutationProto.ColumnValue.QualifierValue.delete_type:type_name -> virogg.hbasecop.hbase.v1.MutationProto.DeleteType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hbase_Client_proto_init() }
func file_hbase_Client_proto_init() {
	if File_hbase_Client_proto != nil {
		return
	}
	file_hbase_HBase_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hbase_Client_proto_rawDesc), len(file_hbase_Client_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hbase_Client_proto_goTypes,
		DependencyIndexes: file_hbase_Client_proto_depIdxs,
		EnumInfos:         file_hbase_Client_proto_enumTypes,
		MessageInfos:      file_hbase_Client_proto_msgTypes,
	}.Build()
	File_hbase_Client_proto = out.File
	file_hbase_Client_proto_goTypes = nil
	file_hbase_Client_proto_depIdxs = nil
}
