// SPDX-License-Identifier: Apache-2.0
//
// Vendored from apache/hbase rel/2.5.10 — see proto/hbase/UPSTREAM.md.
// Slim subset: TableName, TimeRange, ColumnFamilyTimeRange, NameBytesPair,
// RegionSpecifier, ServerName, RegionInfo. Other upstream messages are
// dropped until later tasks need them; field numbers stay byte-identical
// to upstream so this is wire-compatible with HBase itself.

//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// File contains protos that are shared throughout the rest of the
// proto files (Cell.proto, Client.proto, et al) -- in fact, HBase.proto
// is the only proto that other protos may import (others are leaves).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hbase/HBase.proto

package hbasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionSpecifier_RegionSpecifierType int32

const (
	// <tablename>,<startkey>,<regionId>.<encodedName>
	RegionSpecifier_REGION_NAME RegionSpecifier_RegionSpecifierType = 1
	// hash of <tablename>,<startkey>,<regionId>
	RegionSpecifier_ENCODED_REGION_NAME RegionSpecifier_RegionSpecifierType = 2
)

// Enum value maps for RegionSpecifier_RegionSpecifierType.
var (
	RegionSpecifier_RegionSpecifierType_name = map[int32]string{
		1: "REGION_NAME",
		2: "ENCODED_REGION_NAME",
	}
	RegionSpecifier_RegionSpecifierType_value = map[string]int32{
		"REGION_NAME":         1,
		"ENCODED_REGION_NAME": 2,
	}
)

func (x RegionSpecifier_RegionSpecifierType) Enum() *RegionSpecifier_RegionSpecifierType {
	p := new(RegionSpecifier_RegionSpecifierType)
	*p = x
	return p
}

func (x RegionSpecifier_RegionSpecifierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionSpecifier_RegionSpecifierType) Descriptor() protoreflect.EnumDescriptor {
	return file_hbase_HBase_proto_enumTypes[0].Descriptor()
}

func (RegionSpecifier_RegionSpecifierType) Type() protoreflect.EnumType {
	return &file_hbase_HBase_proto_enumTypes[0]
}

func (x RegionSpecifier_RegionSpecifierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RegionSpecifier_RegionSpecifierType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RegionSpecifier_RegionSpecifierType(num)
	return nil
}

// Deprecated: Use RegionSpecifier_RegionSpecifierType.Descriptor instead.
func (RegionSpecifier_RegionSpecifierType) EnumDescriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{2, 0}
}

// *
// Table Name
type TableName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     []byte                 `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	Qualifier     []byte                 `protobuf:"bytes,2,req,name=qualifier" json:"qualifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableName) Reset() {
	*x = TableName{}
	mi := &file_hbase_HBase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableName) ProtoMessage() {}

func (x *TableName) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableName.ProtoReflect.Descriptor instead.
func (*TableName) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{0}
}

func (x *TableName) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *TableName) GetQualifier() []byte {
	if x != nil {
		return x.Qualifier
	}
	return nil
}

// *
// Protocol buffer version of RegionInfo.
type RegionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      *uint64                `protobuf:"varint,1,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	TableName     *TableName             `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Offline       *bool                  `protobuf:"varint,5,opt,name=offline" json:"offline,omitempty"`
	Split         *bool                  `protobuf:"varint,6,opt,name=split" json:"split,omitempty"`
	ReplicaId     *int32                 `protobuf:"varint,7,opt,name=replica_id,json=replicaId,def=0" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for RegionInfo fields.
const (
	Default_RegionInfo_ReplicaId = int32(0)
)

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	mi := &file_hbase_HBase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{1}
}

func (x *RegionInfo) GetRegionId() uint64 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *RegionInfo) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *RegionInfo) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RegionInfo) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RegionInfo) GetOffline() bool {
	if x != nil && x.Offline != nil {
		return *x.Offline
	}
	return false
}

func (x *RegionInfo) GetSplit() bool {
	if x != nil && x.Split != nil {
		return *x.Split
	}
	return false
}

func (x *RegionInfo) GetReplicaId() int32 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return Default_RegionInfo_ReplicaId
}

// *
// Container protocol buffer to specify a region.
// You can specify region by region name, or the hash
// of the region name, which is known as encoded
// region name.
type RegionSpecifier struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          *RegionSpecifier_RegionSpecifierType `protobuf:"varint,1,req,name=type,enum=virogg.hbasecop.hbase.v1.RegionSpecifier_RegionSpecifierType" json:"type,omitempty"`
	Value         []byte                               `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSpecifier) Reset() {
	*x = RegionSpecifier{}
	mi := &file_hbase_HBase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSpecifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSpecifier) ProtoMessage() {}

func (x *RegionSpecifier) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSpecifier.ProtoReflect.Descriptor instead.
func (*RegionSpecifier) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{2}
}

func (x *RegionSpecifier) GetType() RegionSpecifier_RegionSpecifierType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RegionSpecifier_REGION_NAME
}

func (x *RegionSpecifier) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// *
// A range of time. Both from and to are Java time
// stamp in milliseconds. If you don't specify a time
// range, it means all time.  By default, if not
// specified, from = 0, and to = Long.MAX_VALUE
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *uint64                `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To            *uint64                `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_hbase_HBase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetFrom() uint64 {
	if x != nil && x.From != nil {
		return *x.From
	}
	return 0
}

func (x *TimeRange) GetTo() uint64 {
	if x != nil && x.To != nil {
		return *x.To
	}
	return 0
}

// ColumnFamily Specific TimeRange
type ColumnFamilyTimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColumnFamily  []byte                 `protobuf:"bytes,1,req,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,2,req,name=time_range,json=timeRange" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnFamilyTimeRange) Reset() {
	*x = ColumnFamilyTimeRange{}
	mi := &file_hbase_HBase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnFamilyTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnFamilyTimeRange) ProtoMessage() {}

func (x *ColumnFamilyTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnFamilyTimeRange.ProtoReflect.Descriptor instead.
func (*ColumnFamilyTimeRange) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnFamilyTimeRange) GetColumnFamily() []byte {
	if x != nil {
		return x.ColumnFamily
	}
	return nil
}

func (x *ColumnFamilyTimeRange) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

// *
// Protocol buffer version of ServerName
type ServerName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      *string                `protobuf:"bytes,1,req,name=host_name,json=hostName" json:"host_name,omitempty"`
	Port          *uint32                `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	StartCode     *uint64                `protobuf:"varint,3,opt,name=start_code,json=startCode" json:"start_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerName) Reset() {
	*x = ServerName{}
	mi := &file_hbase_HBase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerName) ProtoMessage() {}

func (x *ServerName) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerName.ProtoReflect.Descriptor instead.
func (*ServerName) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{5}
}

func (x *ServerName) GetHostName() string {
	if x != nil && x.HostName != nil {
		return *x.HostName
	}
	return ""
}

func (x *ServerName) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *ServerName) GetStartCode() uint64 {
	if x != nil && x.StartCode != nil {
		return *x.StartCode
	}
	return 0
}

type NameBytesPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameBytesPair) Reset() {
	*x = NameBytesPair{}
	mi := &file_hbase_HBase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameBytesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameBytesPair) ProtoMessage() {}

func (x *NameBytesPair) ProtoReflect() protoreflect.Message {
	mi := &file_hbase_HBase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameBytesPair.ProtoReflect.Descriptor instead.
func (*NameBytesPair) Descriptor() ([]byte, []int) {
	return file_hbase_HBase_proto_rawDescGZIP(), []int{6}
}

func (x *NameBytesPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameBytesPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_hbase_HBase_proto protoreflect.FileDescriptor

const file_hbase_HBase_proto_rawDesc = "" +
	"\n" +
	"\x11hbase/HBase.proto\x12\x18virogg.hbasecop.hbase.v1\"G\n" +
	"\tTableName\x12\x1c\n" +
	"\tnamespace\x18\x01 \x02(\fR\tnamespace\x12\x1c\n" +
	"\tqualifier\x18\x02 \x02(\fR\tqualifier\"\xf5\x01\n" +
	"\n" +
	"RegionInfo\x12\x1b\n" +
	"\tregion_id\x18\x01 \x02(\x04R\bregionId\x12B\n" +
	"\n" +
	"table_name\x18\x02 \x02(\v2#.virogg.hbasecop.hbase.v1.TableNameR\ttableName\x12\x1b\n" +
	"\tstart_key\x18\x03 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x04 \x01(\fR\x06endKey\x12\x18\n" +
	"\aoffline\x18\x05 \x01(\bR\aoffline\x12\x14\n" +
	"\x05split\x18\x06 \x01(\bR\x05split\x12 \n" +
	"\n" +
	"replica_id\x18\a \x01(\x05:\x010R\treplicaId\"\xbb\x01\n" +
	"\x0fRegionSpecifier\x12Q\n" +
	"\x04type\x18\x01 \x02(\x0e2=.virogg.hbasecop.hbase.v1.RegionSpecifier.RegionSpecifierTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x02(\fR\x05value\"?\n" +
	"\x13RegionSpecifierType\x12\x0f\n" +
	"\vREGION_NAME\x10\x01\x12\x17\n" +
	"\x13ENCODED_REGION_NAME\x10\x02\"/\n" +
	"\tTimeRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\"\x80\x01\n" +
	"\x15ColumnFamilyTimeRange\x12#\n" +
	"\rcolumn_family\x18\x01 \x02(\fR\fcolumnFamily\x12B\n" +
	"\n" +
	"time_range\x18\x02 \x02(\v2#.virogg.hbasecop.hbase.v1.TimeRangeR\ttimeRange\"\\\n" +
	"\n" +
	"ServerName\x12\x1b\n" +
	"\thost_name\x18\x01 \x02(\tR\bhostName\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1d\n" +
	"\n" +
	"start_code\x18\x03 \x01(\x04R\tstartCode\"9\n" +
	"\rNameBytesPair\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05valueBb\n" +
	"\x1ccom.virogg.hbasecop.hbase.v1B\vHBaseProtosH\x01Z0github.com/virogg/go-hbase/internal/wire/hbasepb\xa0\x01\x01"

var (
	file_hbase_HBase_proto_rawDescOnce sync.Once
	file_hbase_HBase_proto_rawDescData []byte
)

func file_hbase_HBase_proto_rawDescGZIP() []byte {
	file_hbase_HBase_proto_rawDescOnce.Do(func() {
		file_hbase_HBase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hbase_HBase_proto_rawDesc), len(file_hbase_HBase_proto_rawDesc)))
	})
	return file_hbase_HBase_proto_rawDescData
}

var file_hbase_HBase_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hbase_HBase_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hbase_HBase_proto_goTypes = []any{
	(RegionSpecifier_RegionSpecifierType)(0), // 0: virogg.hbasecop.hbase.v1.RegionSpecifier.RegionSpecifierType
	(*TableName)(nil),                        // 1: virogg.hbasecop.hbase.v1.TableName
	(*RegionInfo)(nil),                       // 2: virogg.hbasecop.hbase.v1.RegionInfo
	(*RegionSpecifier)(nil),                  // 3: virogg.hbasecop.hbase.v1.RegionSpecifier
	(*TimeRange)(nil),                        // 4: virogg.hbasecop.hbase.v1.TimeRange
	(*ColumnFamilyTimeRange)(nil),            // 5: virogg.hbasecop.hbase.v1.ColumnFamilyTimeRange
	(*ServerName)(nil),                       // 6: virogg.hbasecop.hbase.v1.ServerName
	(*NameBytesPair)(nil),                    // 7: virogg.hbasecop.hbase.v1.NameBytesPair
}
var file_hbase_HBase_proto_depIdxs = []int32{
	1, // 0: virogg.hbasecop.hbase.v1.RegionInfo.table_name:type_name -> virogg.hbasecop.hbase.v1.TableName
	0, // 1: virogg.hbasecop.hbase.v1.RegionSpecifier.type:type_name -> virogg.hbasecop.hbase.v1.RegionSpecifier.RegionSpecifierType
	4, // 2: virogg.hbasecop.hbase.v1.ColumnFamilyTimeRange.time_range:type_name -> virogg.hbasecop.hbase.v1.TimeRange
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hbase_HBase_proto_init() }
func file_hbase_HBase_proto_init() {
	if File_hbase_HBase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hbase_HBase_proto_rawDesc), len(file_hbase_HBase_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hbase_HBase_proto_goTypes,
		DependencyIndexes: file_hbase_HBase_proto_depIdxs,
		EnumInfos:         file_hbase_HBase_proto_enumTypes,
		MessageInfos:      file_hbase_HBase_proto_msgTypes,
	}.Build()
	File_hbase_HBase_proto = out.File
	file_hbase_HBase_proto_goTypes = nil
	file_hbase_HBase_proto_depIdxs = nil
}
